version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - "ruzickap"
    default_labels:
      - "dependencies"
      - "submodules"
