name: periodic-broken-links-check

on:
  schedule:
    - cron: '10 10 * * 1'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/periodic-broken-links-check.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/periodic-broken-links-check.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-18.04
    steps:
      - name: Broken link checker
        run: |
          export INPUT_URL="https://${GITHUB_REPOSITORY%/*}.github.io/${GITHUB_REPOSITORY##*/}"
          export INPUT_CMD_PARAMS="--buffer-size=8192 --concurrency=10 --exclude=mylabs.dev"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-broken-link-checker/v1/entrypoint.sh | bash
