name: periodic-broken-link-checks

on:
  schedule:
    - cron: '8 8 * * 2'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/periodic-broken-link-checks.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/periodic-broken-link-checks.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Broken link checker
        env:
          EXCLUDE: |
            mylabs.dev
        run: |
          export INPUT_URL="https://${GITHUB_REPOSITORY%/*}.github.io/${GITHUB_REPOSITORY##*/}"
          export INPUT_CMD_PARAMS="--verbose --buffer-size=8192 --max-connections=10 --exclude=($( echo ${EXCLUDE} | tr ' ' '|' ))"
          wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v1/entrypoint.sh | bash
